language: scala

scala:
  - 2.13.1

services:
  - docker

jobs:
  include:
    - stage: compile
      name: "Compile sources"
      script: sbt checks
    - stage: test
      name: "Unit tests"
      script: sbt test
    - script: sbt integration
      name: "Integration tests"
    - stage: release
      script: sbt 'release-with-defaults'
      name: "Automatic version push"

stages:
  - compile
  - test