# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Pull Request to Master

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: sbt compile
      - name: Check formatting
        run: sbt scalafmtCheck
      - name: Unit tests
        run: sbt test
      - name: Integration tests
        run: sbt integration
      - name: Generate coverage report
        run: sbt coverageReport
